### ISSUE TITLE
Error on Install - no podspec found

### ISSUE THREAD

**Issue by rgoldiez** [forcedotcom/SmartSyncExplorerReactNative#10]
I'm getting the following error when trying to install this.  I realize it may not be official yet, but I'm very interested in this functionality and I'm trying to determine if I need to develop something on my own or if this will work.

[!] No podspec found for `SalesforceMobileSDK-iOS` in `../../external/ios`

![screen shot 2015-12-04 at 5 25 00 am](https://cloud.githubusercontent.com/assets/10797610/11588618/9a96ee9e-9a47-11e5-86e0-e68479d2e085.png)

**Comment by wmathurin** [comment]
Did you run the install.sh script?

**Comment by rgoldiez** [comment]
Yes, that's where that error came from.  Are there other dependencies or requirements that I need to install first?

**Comment by wmathurin** [comment]
You're in the unstable branch right?

**Comment by wmathurin** [comment]
Master won't work anymore because of it points to the unstable version of the repo.
So you should checkout the unstable branch, and run install.sh.
We will soon merge unstable into master when we release 4.0.

**Comment by rgoldiez** [comment]
Yes, I was trying to use the unstable branch.

**Comment by wmathurin** [comment]
The first thing install.sh is to get the submodules.
Could you try that in a terminal:
git submodule init
git submodule sync
git submodule update --init --recursive

Without them you won't have anything in external/ios.

**Comment by rgoldiez** [comment]
I ran each of those git submodule commands and it returns me to the command prompt without doing anything (no errors, no output).  Nothing lands in external/ios.  I do have the .gitmodules file that came down when I cloned the repo.

**Comment by wmathurin** [comment]
What version of git are you running?
Are you on a Mac?

**Comment by rgoldiez** [comment]
git 2.4.9 running on a Mac.

**Comment by wmathurin** [comment]
I'm running git 2.5.3, could you upgrade and try again?

**Comment by rgoldiez** [comment]
I installed the latest git (2.6.2) on my Mac... running into the same problem.

**Comment by wmathurin** [comment]
Not sure what's going on.
Try deleting your clone. Re-clone it, and retry install.sh.

**Comment by rgoldiez** [comment]
Progress!  I wiped the clone and started over - `./install.sh` worked this time!

I went into `app/` and did `npm start`

Then launched Xcode and tried to run the demo app.  I get this link error:

<img width="879" alt="screen shot 2015-12-04 at 4 29 11 pm" src="https://cloud.githubusercontent.com/assets/10797610/11603031/6f6b53ce-9aa4-11e5-9892-13be551ebd31.png">

**Comment by wmathurin** [comment]
If you go into app/ios and do a:

``` shell
pod update
```

Do you see the following:

``` shell
Update all pods
Updating local specs repositories
Analyzing dependencies
Fetching podspec for `React` from `../node_modules/react-native`
Fetching podspec for `SalesforceMobileSDK-iOS` from `../../external/ios`
Removing FMDB
Downloading dependencies
Using CocoaLumberjack (2.2.0)
Using React (0.16.0-rc)
Using SQLCipher (3.1.0)
Installing SalesforceMobileSDK-iOS 4.0.0 (was 4.0.0)
Generating Pods project
```

**Comment by rgoldiez** [comment]
I am getting that when running `pod update`.  My probably was I was opening the Xcode project in the `ios` directory instead of opening the directory.  

Now, when I try to run the demo app, I get the following error (FMDatabase.h not found).  Any ideas?  I appreciate all your help.

<img width="376" alt="screen shot 2015-12-04 at 9 09 06 pm" src="https://cloud.githubusercontent.com/assets/10797610/11605680/8c7cbb7a-9acb-11e5-881c-7a388b925b2a.png">

**Comment by wmathurin** [comment]
You need to open the workspace generated by cocoapod (or open the folder
which does the same)

**Comment by rgoldiez** [comment]
That's what I had done.  Just to be clear, I'm opening `app/ios` folder in Xcode.  Still getting the same error.

**Comment by rgoldiez** [comment]
Got this to work on my other Mac.  Not sure what the problem was on my laptop.... thanks for helping me out.
