### ISSUE TITLE
moveCursorToNextPage crashed on iOS

### ISSUE THREAD

**Issue by booker0108** [forcedotcom/SmartSyncExplorerReactNative#105]
I have run a smart sql and get the cursor from the callback.

When I try to use 

`smartstore.moveCursorToNextPage(false, cursor, result=>console.log(result))`

it results in 

`
Exception '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[1]' was thrown while invoking moveCursorToPageIndex on target SFSmartStoreReactBridge with params (
        {
        cursorId = 0x60000048a000;
        index = 1;
        isGlobalStore = 0;
    },
    31
)
`

**Comment by wmathurin** [comment]
Fixed by https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2177
