### ISSUE TITLE
Apex Rest - 'Resource does not exist' only from this example app

### ISSUE THREAD

**Issue by rgoldiez** [forcedotcom/SmartSyncExplorerReactNative#19]
I have a fairly simple apex class exposed as an API, with a @HttpGet method contained within the class.  I can get a successful response from the apex rest API when access via both the nforce (node.js library for force.com) and apigee's web based API console (https://apigee.com/console/salesforce_sandbox).

However, when I tried to access the apex rest API from this example React Native app, I get the dreaded 404 resource does not exist.  I created a simple function in `force.react.net.js` that does not specify the `/services/apexrest/` so that I could experience with the function call.

```
var apexRest = function(restclass, callback, error) {
    return exec(restclass 
                     , callback, error);
};
```

Calling this function for my apex rest method spits the following to console and it **results in a 404 error**.

```
SFNetReactBridge.sendRequest called: {"path":"/services/apexrest/UserDefaults/","method":"GET","queryParams":{},"headerParams":{}}
```

If instead I call the same function with a rest query, like below, I get **success** and results come back:

```
SFNetReactBridge.sendRequest called: {"path":"/services/data/v35.0/query?q=SELECT%20Name%20from%20Account","method":"GET","queryParams":{},"headerParams":{}}
```

If I call the same apex rest resource from apigee's console, I get success as shown below (private info pixelated out):

![screen shot 2015-12-20 at 9 26 12 am](https://cloud.githubusercontent.com/assets/10797610/11918559/29816740-a6fc-11e5-85a3-626a9cfbbf89.png)

Any ideas why this isn't working from this example app?

**Comment by wmathurin** [comment]
We will investigate and let you know what we find out.

**Comment by rgoldiez** [comment]
Thank you.

**Comment by wmathurin** [comment]
The way things are wired right now, it expects the path to be relative to /services/data, so with your code it's actually trying to call /services/data/servicesapexrest/UserDefaults which explains the 404.
We will try and address this limitation in our next release.

**Comment by rgoldiez** [comment]
Thanks for checking it out and the feedback.  

Just to make sure we're on the same page, I added the following to `react.force.net.js` so that I can call my custom REST api with this function.

```
var apexRest = function(restclass, callback, error) {
    return exec('/services/apexrest' + restclass
                     , callback, error);
};
```

So, you're saying that even though I'm building a path of /services/apexrest/[my-rest-api] the underlying SDK is prepending the path with /services/data ?

**Comment by wmathurin** [comment]
Basically, the path that exec takes is expected to be relative to /services/data.
It's changed in unstable, see:
https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/1323
https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/1023
https://github.com/forcedotcom/SalesforceMobileSDK-Shared/pull/316

Also with https://github.com/forcedotcom/SalesforceMobileSDK-Shared/pull/317, I'm exposing a generic "sendRequest" method in the react.force.net module.

The unstable branch for SmartSyncExplorerReactNative points to that code as well.

**Comment by rgoldiez** [comment]
Confirmed.  I pulled in the changes in the commits to the app I'm working on and these changes worked.  Thanks so much for promptly addressing this!
