### ISSUE TITLE
SQLite issue with latest unstable

### ISSUE THREAD

**Issue by rgoldiez** [forcedotcom/SmartSyncExplorerReactNative#21]
Thanks for addressing the issue associated with calling apex rest APIs.  I cloned the this unstable repo to test again my custom api, but I'm running into the following error to the standard `SmartSyncExplorerReactNative` example app.

![screen shot 2016-01-07 at 1 58 05 pm](https://cloud.githubusercontent.com/assets/10797610/12181271/d9e57ee8-b546-11e5-911e-3f27d475ba24.png)

I cloned the unstable repo, ran the install script, launched npm start and get the above error message in the console after login.  No contacts show up in the example app.  Any ideas what's going on?  Am I missing a step?

**Comment by wmathurin** [comment]
That means the SQLCipher that gets used in your app wasn't compiled with FTS (the full-text search extension). Let me check if we lost that flag in the podspec in unstable.

**Comment by wmathurin** [comment]
Please get the latest from unstable.
It should now work (because of https://github.com/forcedotcom/SmartSyncExplorerReactNative/commit/860ab1704a3a33cf20fb36c9b52d8e530ef0bade specifically).

**Comment by wmathurin** [comment]
Make sure to re-run install.sh
Let me know if you run into any issues.
