### ISSUE TITLE
Support for latest React Native?

### ISSUE THREAD

**Issue by rgoldiez** [forcedotcom/SmartSyncExplorerReactNative#25]
Any plans to support the latest release of React Native?  I tried moving to 0.17 but it has some breaking changes to RCTRootView.

**Comment by wmathurin** [comment]
Unfortunately, from one point release to the next of react native, there are always breaking changes. So you can't simply point to a new version and have the native modules to compile.
We plan to keep up as much as possible but our point releases are less frequent than react native's. With our next point release, we will make sure to support what ever react native release is out at that point.

**Comment by rgoldiez** [comment]
Makes sense.  Looking forward to the next point release :smile:
