### ISSUE TITLE
Possible to send binary data across sendRequest?

### ISSUE THREAD

**Issue by rgoldiez** [forcedotcom/SmartSyncExplorerReactNative#30]
I'm working with the SDK and trying to send a file/photo to the chatter REST API.  Is this possible with sendRequest?

**Comment by wmathurin** [comment]
The native code in the SDK supports binary payloads. But you can't do it right now with sendRequest the way it's wired through.

**Comment by rgoldiez** [comment]
Any comment as to when this will be supported by the React Native bridge?  Or, any tips or places to go if I want to start hacking at it myself?

**Comment by wmathurin** [comment]
We have a number of files related support methods (upload and download) in https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/libs/SalesforceRestAPI/SalesforceRestAPI/Classes/SFRestAPI%2BFiles.m.
Those are the ones you want to be calling from new methods in the net react bridge.

**Comment by rgoldiez** [comment]
My eyes start to glaze over when I look at Obj C..... is this on your roadmap and, if so, any idea when we would see it?  You know I'm willing to alpha test anything :smile:

**Comment by wmathurin** [comment]
It's on our backlog but we don't have a date/release for it yet.

**Comment by wmathurin** [comment]
Would you be passing binary through or a path to a local file (e.g. photo)?

**Comment by rgoldiez** [comment]
Path to local file.

**Comment by wmathurin** [comment]
It's done in unstable for ios.
For an example, please check out: https://github.com/wmathurin/MyUserPicReactNative

**Comment by rgoldiez** [comment]
This is great news!  How do I update my project to point to 4.1.1 unstable?

**Comment by rgoldiez** [comment]
I think I figured it out (unless you advise otherwise):

I edited my `.gitmodules` to add a `branch = unstable` line to each submodule.
I then ran `git submodule update --remote`
I then re-ran `./install.sh`

**Comment by rgoldiez** [comment]
@wmathurin - Not sure if this is the correct place to post this, but I upgrade from 4.0.2 -> 4.2.0 (unstable) and the salesforce login endpoint is not honoring my custom endpoint for our salesforce community: robots.hirebotics.com

Another issue I see is that the OAuth view for login now presents the user with a gear in the upper right where they can choose which endpoint they want...... in our case we only want our community and we want to **not** give our customers the ability to change to some other endpoint.  

Are there instructions on how to set this up similar to how it was before (i.e., honor our custom endpoint in Info.plist and hide the ability to change endpoints)?

**Comment by rgoldiez** [comment]
Additional observation:  If I delete the app and re-run it in the simulator, the app correctly routes to our custom endpoint.  The Navbar is still there (screenshot below), which I don't like.  So, does this mean our users would have to delete the app and reinstall it?  Also, if they tap the gear, it immediately takes them to the login.salesforce.com endpoint and they have no way of getting back to our endpoint.

<img width="374" alt="screen shot 2016-03-15 at 11 22 56 am" src="https://cloud.githubusercontent.com/assets/10797610/13785146/4d89700a-eaa0-11e5-8452-a1885914cf9c.png">

**Comment by kchitalia** [comment]
@rgoldiez At present the gear icon is shown by default. But we can provide a way to override that in our next release.

@wmathurin

**Comment by rgoldiez** [comment]
@kchitalia - Thanks for the feedback.  Any comments on the other issue I ran into - that is, it appears that there are some issues with custom oauth endpoints (ie, communities):
- It appears that if our app is already installed, 4.2 kicks you back to the login screen (not a pleasant experience) but worse is that it appears that the user would have to delete the app and re-install it to get directed to the community endpoint.
- If they erroneously tap the gear, they can't get back to the community endpoint.

**Comment by rgoldiez** [comment]
@kchitalia - Any update on hiding the login navbar and gear icon?

**Comment by kchitalia** [comment]
@rgoldiez If you get the latest from unstable you should see this. Please take a look at the RestApiExplorer sample app. There is sample code in there to hide the nav bar and gear icon.

**Comment by rgoldiez** [comment]
@kchitalia - Thanks for the response.  I have the very lastest of 4.2.0 unstable (as of this morning).  I found the following code in AppDelegate, but when I uncomment the SFLoginViewController.. line, I get the error further below.  Any idea what I'm doing wrong?  Also, is the a simple setting to just turn off the navBar (it wasn't obvious to me when I looked [here](http://forcedotcom.github.io/SalesforceMobileSDK-iOS/Documentation/SalesforceSDKCore/html/Classes/SFLoginViewController.html), but I am weak with Obj C).  Appreciate your help!

```
    //
    //Uncomment the code below to see how you can customize the color, textcolor, font and fontsize of the navigation bar
    //
    //SFLoginViewController *loginViewController = [SFLoginViewController sharedInstance];
    // Set primary color to different color to style the navigation header
    //loginViewController.navBarColor = [UIColor colorWithRed:0.051 green:0.765 blue:0.733 alpha:1.0];
    //loginViewController.navBarFont = [UIFont fontWithName:@"Helvetica" size:16.0];
    //loginViewController.navBarTextColor = [UIColor blackColor];
    //
```

![screen shot 2016-04-05 at 1 11 06 pm](https://cloud.githubusercontent.com/assets/10797610/14292976/0de31ef6-fb30-11e5-8919-a4b4afe7e724.png)

**Comment by rgoldiez** [comment]
@kchitalia - I got past the error (I had missed the import up top), but I'm still unsure about how to simply hide the NavBar.

**Comment by kchitalia** [comment]
There should be a property called showNavbar in the login viewcontroller.
To hide the navbar set it to NO

Sent from my iPhone

On Apr 5, 2016, at 11:27 AM, Rob Goldiez notifications@github.com wrote:

@kchitalia https://github.com/kchitalia - I got past the error (I had
missed the import up top), but I'm still unsure about how to simply hide
the NavBar.

**Comment by rgoldiez** [comment]
@kchitalia - Thank you for the part.  When I try to compile my project I get the following error.  If I comment out the two lines added to hide the navbar on the LoginViewController, this error goes away (but I get the navbar).  

![screen shot 2016-04-05 at 2 38 01 pm](https://cloud.githubusercontent.com/assets/10797610/14295644/12c7096c-fb3c-11e5-812b-cefc5b23b428.png)

**Comment by wmathurin** [comment]
@kchitalia Looks like SFApplicationHelper.h is not in SalesforceSDKCore.podspec.

**Comment by kchitalia** [comment]
@wmathurin Looks like this class was added recently in some other pull request but not added in the podspec, let me add it to SalesforceSDKCore.podspec. Will send out a new pull request for that.

**Comment by rgoldiez** [comment]
Appreciate it @wmathurin and @kchitalia ... looking forward to the podspec update so I can continue with my testing.

**Comment by rgoldiez** [comment]
@wmathurin - I finally got to testing the binary uploads.  Works well for profile pics, as shown in the demo repo, but if I try to modify the endpoint to chatter files for the current user, I get the following error in the console.  Any tips on posting a binary file (image) to chatter files to then reference in a chatter post (which I believe is the required steps as of v36 of the api)?  Thanks.

```
SFNetReactBridge.sendRequest failed: {"message":"sendRequest failedError Domain=CSFNetworkErrorDomain Code=400 \"Binary data expected with name \"fileData\"\" UserInfo={NSLocalizedFailureReason=POST_BODY_PARSE_ERROR, isAuthenticationFailure=false, NSLocalizedDescription=Binary data expected with name \"fileData\", action=<SFRestAPISalesforceAction: 0x7faa1f8850a0, POST \"/connect/communities/0DB6100000000KLGAY/files/users/me\" (0.00)>}"}
```

**Comment by wmathurin** [comment]
What was the value of the fileParams argument for your sendRequest call?

-W

**Comment by rgoldiez** [comment]
No change from the user profile example.  I simply changed the endpoint as shown below.  I'm sure I'm missing something obvious.

```
    var path = '/v36.0/connect/communities/' + getUserInfo().community + '/files/users/me'
    forceNet.sendRequest('/services/data', path,
                           function(response) {
                                console.log(JSON.stringify(response));
                                callback(response);
                           },
                           function(error) {
                                console.log('Failed to upload user photo:' + error);
                           },
                           'POST',
                           {},
                           {'X-Connect-Bearer-Urls': 'true'},
                           {fileUpload: {fileUrl:localPhotoUrl, fileMimeType:'image/jpeg', fileName:'pic.jpg'}}
                           );
```

**Comment by rgoldiez** [comment]
I figured it out... the `fileUpload` key needs to be `fileData`

**Comment by wmathurin** [comment]
Yep that's it.
