### ISSUE TITLE
Delayed oauth w/ SDK?

### ISSUE THREAD

**Issue by rgoldiez** [forcedotcom/SmartSyncExplorerReactNative#36]
I'd like to wire up part of my React Native app (actually, a separately registered component in the AppRegistry of RN) to run before the SDK presents the login view to the user.  Can you point me to the best place (I assume in App Delegate) to insert this?

**Comment by wmathurin** [comment]
Indeed it's happening in the AppDelegate.m.
https://github.com/forcedotcom/SmartSyncExplorerReactNative/blob/master/app/ios/SmartSyncExplorerReactNative/AppDelegate.m

Move line 83

```
 [[SalesforceSDKManager sharedManager] launch];
```

from application:didFinishLaunchingWithOptions to wherever it makes sense.

You also need to see whether setupReactRootView which is currently called from setupRootViewController which is called from the [SalesforceSDKManager sharedManager].postLaunchAction, needs to happen sooner.

**Comment by wmathurin** [comment]
It's done in unstable.
It's demonstrated in the sample app here: https://github.com/wmathurin/MyUserPicReactNative/
The key changes are here: https://github.com/wmathurin/MyUserPicReactNative/pull/3/files

**Comment by rgoldiez** [comment]
Awesome!  This is a great solution and I was able to verify functionality with a simple test using 4.2.0 unstable.  Thanks so much!
