### ISSUE TITLE
Not able to build the app; npm start not working

### ISSUE THREAD

**Issue by irabanerjee** [forcedotcom/SmartSyncExplorerReactNative#40]
Hi, 
 I have installed the app, have run the install command and it got installed successfully. Next command 'npm start' is giving the following error as mentioned below. 
I am using Windows 7 and running the same as Administrator.This is high priority.

The npm debug log is as follows:
0 info it worked if it ends with ok
1 verbose cli [ 'D:\Software\Node_js\node.exe',
1 verbose cli   'D:\Software\Node_js\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.7.3
3 info using node@v5.9.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle SmartSyncExplorerReactNative@0.0.1~prestart: SmartSyncExplorerReactNative@0.0.1
6 silly lifecycle SmartSyncExplorerReactNative@0.0.1~prestart: no script for prestart, continuing
7 info lifecycle SmartSyncExplorerReactNative@0.0.1~start: SmartSyncExplorerReactNative@0.0.1
8 verbose lifecycle SmartSyncExplorerReactNative@0.0.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle SmartSyncExplorerReactNative@0.0.1~start: PATH: D:\Software\Node_js\node_modules\npm\bin\node-gyp-bin;D:\Sandbox\SmartSyncExplorerReactNative\app\node_modules.bin;D:\Software\Node_js;C:\Users\531319\AppData\Roaming\npm;D:\Software\Node_js\;C:\ProgramData\Oracle\Java\javapath;D:\jdk\bin;C:\Program Files\Git\bin;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\OpenCL SDK\2.0\bin\x86;D:\Software\Node js\;C:\Program Files\gradle-2.12\bin;D:\Android\SDK\tools;D:\Android\SDK\platform_tools;C:\Users\531319\AppData\Roaming\npm;D:\Software\Node_js
10 verbose lifecycle SmartSyncExplorerReactNative@0.0.1~start: CWD: D:\Sandbox\SmartSyncExplorerReactNative\app
11 silly lifecycle SmartSyncExplorerReactNative@0.0.1~start: Args: [ '/d /s /c',
11 silly lifecycle   'node_modules/react-native/packager/packager.sh --root js' ]
12 silly lifecycle SmartSyncExplorerReactNative@0.0.1~start: Returned: code: 1  signal: null
13 info lifecycle SmartSyncExplorerReactNative@0.0.1~start: Failed to exec start script
14 verbose stack Error: SmartSyncExplorerReactNative@0.0.1 start: `node_modules/react-native/packager/packager.sh --root js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (D:\Software\Node_js\node_modules\npm\lib\utils\lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (D:\Software\Node_js\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid SmartSyncExplorerReactNative@0.0.1
16 verbose cwd D:\Sandbox\SmartSyncExplorerReactNative\app
17 error Windows_NT 6.1.7601
18 error argv "D:\Software\Node_js\node.exe" "D:\Software\Node_js\node_modules\npm\bin\npm-cli.js" "start"
19 error node v5.9.0
20 error npm  v3.7.3
21 error code ELIFECYCLE
22 error SmartSyncExplorerReactNative@0.0.1 start: `node_modules/react-native/packager/packager.sh --root js`
22 error Exit status 1
23 error Failed at the SmartSyncExplorerReactNative@0.0.1 start script 'node_modules/react-native/packager/packager.sh --root js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the SmartSyncExplorerReactNative package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node_modules/react-native/packager/packager.sh --root js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs SmartSyncExplorerReactNative
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls SmartSyncExplorerReactNative
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by wmathurin** [comment]
@kchitalia have you ever encountered the problem above?

**Comment by kchitalia** [comment]
I have not come across this problem, but let me dig into this and see whats going on.

**Comment by irabanerjee** [comment]
FYI, I am using latest version of Node JS. The above is npm-debug log. The error coming at console is as follows (Just in case this helps you to debug the issue):
D:\Sandbox\SmartSyncExplorerReactNative\app>npm start

> SmartSyncExplorerReactNative@0.0.1 start D:\Sandbox\SmartSyncExplorerReactNative\app
> node_modules/react-native/packager/packager.sh --root js

'node_modules' is not recognized as an internal or external command, operable program or batch file.

**Comment by wmathurin** [comment]
We have not seen the issue here, so you might want to troubleshoot your react native installation.
A good starting point: https://facebook.github.io/react-native/docs/troubleshooting.html
