### ISSUE TITLE
Running this repo on Android

### ISSUE THREAD

**Issue by rgoldiez** [forcedotcom/SmartSyncExplorerReactNative#47]
I'm new to the Android side of things, so forgive me if I'm doing something obviously wrong...

I cloned this repo, ran `./install.sh`, launched the react native package manager (`npm start`), and brought up Android Studio.  When I go to run in the simulator, I get the following error.

Any idea what I'm doing wrong?

```
FATAL EXCEPTION: main
Process: com.salesforce.samples.smartsyncexplorerreactnative, PID: 2383
android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@e08b7a0 -- permission denied for this window type
    at android.view.ViewRootImpl.setView(ViewRootImpl.java:591)
    at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:310)
    at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
    at android.app.Dialog.show(Dialog.java:319)
    at com.facebook.react.devsupport.DevSupportManagerImpl.handleReloadJS(DevSupportManagerImpl.java:588)
    at com.facebook.react.ReactInstanceManagerImpl$3$1.run(ReactInstanceManagerImpl.java:380)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5417)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by wmathurin** [comment]
That should work in the latest code.

The dev menu uses a SystemAlertWindow which requires a permission. On Android 6, the user must be prompted for that permission. That happens in ReactActivity which is the super class of SalesforceReactActivity which is the super class of MainActivity.

If you code is older look at the workaround here: https://github.com/facebook/react-native/issues/4043

**Comment by rgoldiez** [comment]
Thanks @wmathurin .... looking at the workaround now.

Just to be clear, though, I hit this issue with a fresh install of this repo.... so I should be getting the latest code for this example.

**Comment by wmathurin** [comment]
Hmm, and what Android version is running on the emulator?

**Comment by rgoldiez** [comment]
23...

![image](https://cloud.githubusercontent.com/assets/10797610/16636197/3857ee82-439c-11e6-812f-aabea5e2cc29.png)

**Comment by wmathurin** [comment]
I see the crash when launching some times but at other times I see the "Draw over other apps" permission screen pop up.

Either way, if I go to settings > draw over other apps and change it to yes for SmartSyncExplorerReactNative, then restart the application, then it works fine.

I believe that it is only an issue when the dev menu is enabled, to disable it add:

``` java
@Override
protected boolean getUseDeveloperSupport() { 
    return false; 
}
```

in the MainActivity.java.

In dev, you probably want the dev menu, so you will have to go to the permission screen.
In prod, it should work fine.

@rwhitley should we doc that?
@bhariharan is there a more elegant approach?

**Comment by rgoldiez** [comment]
@wmathurin - Thanks!  That worked.

**Comment by rgoldiez** [comment]
@wmathurin - Not sure where to post this... so please let me know if I should move it elsewhere....

I'm trying to get my app (based on this repo as a starting point) working on Android and I'm running into this compile error in MainActivity.java.

My project is on RN 0.29.2 and I'm using the Salesforce SDK 4.2.0 (stable/official).

![screen shot 2016-07-20 at 8 31 55 am](https://cloud.githubusercontent.com/assets/10797610/16988296/91090700-4e55-11e6-9a47-c11c7a1b65ef.png)

**Comment by rgoldiez** [comment]
It seems that they made a [breaking change](https://github.com/facebook/react-native/releases/tag/v0.29.0) with RN 0.29.x 

... any idea what this repo will be updated to RN 0.29.x? 😊

**Comment by wmathurin** [comment]
With https://github.com/forcedotcom/SmartSyncExplorerReactNative/pull/53, SmartSyncExplorerReactNative now uses react native 0.30.0

**Comment by rgoldiez** [comment]
Awesome.... thanks!
