### ISSUE TITLE
sendRequest on Android throwing a URISyntaxException

### ISSUE THREAD

**Issue by rgoldiez** [forcedotcom/SmartSyncExplorerReactNative#48]
See output log below.  Trying to call my custom apex REST endpoint on android and I'm seeing the following exception (screenshot first, followed by text below).  This `sendRequest` works fine on the iOS side.

![image](https://cloud.githubusercontent.com/assets/10797610/17060367/3e99d92c-4fef-11e6-88c9-4d5a7bfaedf0.png)

```
07-22 09:19:46.584 10076-10099/com.salesforce.samples.smartsyncexplorerreactnative I/ReactNativeJS: SalesforceNetReactBridge.sendRequest called: {"endPoint":"/services/apexrest/","path":"v1.0/AppDefaults/?AppVersion=1.0 (build 1)&CodePush=n/a","method":"GET","queryParams":{},"headerParams":{},"fileParams":{}}
07-22 09:19:46.590 10076-10099/com.salesforce.samples.smartsyncexplorerreactnative W/ReactNativeJS: Warning: In next release empty section headers will be rendered. In this release you can use 'enableEmptySections' flag to render empty section headers.
07-22 09:19:46.590 10076-10099/com.salesforce.samples.smartsyncexplorerreactnative W/ReactNativeJS: Warning: In next release empty section headers will be rendered. In this release you can use 'enableEmptySections' flag to render empty section headers.
07-22 09:19:46.591 10076-10099/com.salesforce.samples.smartsyncexplorerreactnative W/ReactNativeJS: Warning: In next release empty section headers will be rendered. In this release you can use 'enableEmptySections' flag to render empty section headers.
07-22 09:19:46.651 10076-10100/com.salesforce.samples.smartsyncexplorerreactnative E/ClientInfo: resolveUrl: URISyntaxException thrown on URL: https://bots.my.salesforce.com/services/apexrest/v1.0/AppDefaults/?AppVersion=1.0 (build 1)&CodePush=n/a
```

**Comment by rgoldiez** [comment]
I'm seeing a similar issue when calling sendRequest to my endpoint on Android from this example app:

![image](https://cloud.githubusercontent.com/assets/10797610/17067610/1d05a066-5012-11e6-826d-d3bd17e97e66.png)

**Comment by helenren** [comment]
@rgoldiez what's the SDK version you are using? Thanks.

**Comment by rgoldiez** [comment]
The official SDK 4.2.0

**Comment by rgoldiez** [comment]
I should add that a `sendRequest` on android to a standard, salesforce provided API seems to work fine.  But when I try to hit a custom rest API, it throws the exception.  No issues at all on the iOS side.

**Comment by rgoldiez** [comment]
@wmathurin - tagging you to make sure you've seen this issue.  I'm stuck.  If I do a send request to an standard salesforce object on android, I get the expected response.  When I hit a custom API, bad things happen.

This works fine:

```
forceNet.sendRequest('/services/data/', 'v36.0/sobjects/Account/0016100000SjOwF',
   (resp) => {
      console.log('-------------------------- account query --------------------------------')
      console.log(resp)
      console.log('-------------------------- account query --------------------------------')
   },
   (err) => {
      console.log('-------------------------- account err ----------------------------------')
      console.log(err)
      console.log('-------------------------- account err ----------------------------------')
   }
)
```

This does not work at all on Android (works fine on iOS)...

```
forceNet.sendRequest('/services/apexrest/', 'v1.0/AppDefaults',
   (resp) => {
      console.log('-------------------------- custom api -----------------------------------')
      console.log(resp)
      console.log('-------------------------- custom api -----------------------------------')
   },
   (err) => {
      console.log('-------------------------- custom err -----------------------------------')
      console.log(err)
      console.log('-------------------------- custom err -----------------------------------')
   }
)

```

**Comment by rgoldiez** [comment]
Just to add... the code below works fine on android... that is, getting the oauth token from the Salesforce bridge and manually preparing a `fetch` with the React Native library gives me back the appropriate response.  But using `sendReqeust` (as noted earlier on this issue) throws an exception in android only and only with a custom rest api.

... adding @bhariharan in case @wmathurin is out of pocket.

```
var forceOAuth = require('./react.force.oauth.js');

forceOAuth.getAuthCredentials(
   (success) => {
      fetch('https://bots.my.salesforce.com/services/apexrest/v1.0/AppDefaults',
         {
            method: 'GET',
            headers: {
               'Authorization': 'Bearer '+success.accessToken,
            },
         })
         .then((response) => {
            console.log('-------------------------- custom fetch -----------------------------------')
            console.log(response);
            console.log('-------------------------- custom fetch -----------------------------------')
         })
         .catch((error) => {
            console.log('-------------------------- custom fetch error -----------------------------------')
            console.log(error);
            console.log('-------------------------- custom fetch error -----------------------------------')
         })
   },
   (err) => {
      console.log('-------------------------- token error -----------------------------------')
      console.log(err)
      console.log('-------------------------- token error -----------------------------------')
   }
)
```

**Comment by bhariharan** [comment]
@rgoldiez Sorry for the delayed response.

I noticed in your first screenshot that `path = v1.0/AppDefaults/?AppVersion=1.0 (build 1)&CodePush=n/a`. There are 2 things that stand out to me here:
1. There's a `/` followed by a `?` after `AppDefaults`, but this should probably be okay.
2. There's a blank space between `1.0` and `(build1)`, and it doesn't appear to be escaped or URI encoded.

Could you log the full URI of the request when you manually prepare `fetch` yourself and when you use `sendRequest`? I'm curious what's different.

**Comment by rgoldiez** [comment]
@bhariharan - Thanks for the response.  I use the optional parameters in the URL to update the user's profile in Salesforce to know who's on what version of the app and CodePush (MS's tool for deploying javascript updates).  They aren't required by the rest api and everything works fine on iOS.

My 

To see if the URL params were causing an issue, I dropped the optional params and still ran into the same issue (this is adding the `sendRequest` to my custom API from this repo, not my app):

code added to `componentDidMount` of this repo:

```
var forceNet = require('./react.force.net.js');
//...
 componentDidMount: function() {
   //   storeMgr.syncData();
     forceNet.sendRequest('/services/apexrest/','v1.0/AppDefaults/',
        (resp) => {
           console.log('--> SUCCESS from API AppDefaults')
        },
        (err) => {
           console.log('--> ERROR from API AppDefaults ...')
           console.log(err)
        }
     )
 }
```

Output log:
![image](https://cloud.githubusercontent.com/assets/10797610/17235729/080df5f4-5509-11e6-869e-66803e03028c.png)

**Comment by rgoldiez** [comment]
If I change `componentDidMount` in this repo to the follow, I get back the expected response:

```
var forceNet = require('./react.force.net.js');
var forceOAuth = require('./react.force.oauth.js');
//...
 componentDidMount: function() {
   //   storeMgr.syncData();
   //   forceNet.sendRequest('/services/apexrest/','v1.0/AppDefaults/',
   //      (resp) => {
   //         console.log('--> SUCCESS from API AppDefaults')
   //      },
   //      (err) => {
   //         console.log('--> ERROR from API AppDefaults ...')
   //         console.log(err)
   //      }
   //   )

   forceOAuth.getAuthCredentials(
      (success) => {
         fetch('https://bots.my.salesforce.com/services/apexrest/v1.0/AppDefaults/',
            {
               method: 'GET',
               headers: {
                  'Authorization': 'Bearer '+success.accessToken,
               },
            })
            .then(response => response.json())
            .then((responseJson) => {
               console.log('-------------------------- custom fetch -----------------------------------')
               console.log(responseJson);
               console.log('-------------------------- custom fetch -----------------------------------')
            })
            .catch((err) => {
               console.log('-------------------------- custom fetch error -----------------------------------')
               console.log(error);
               console.log('-------------------------- custom fetch error -----------------------------------')
            })
      },
      (err) => {
         console.log('-------------------------- token error -----------------------------------')
         console.log(err)
         console.log('-------------------------- token error -----------------------------------')
      }
   )

 }
```

![image](https://cloud.githubusercontent.com/assets/10797610/17235847/dcba9262-5509-11e6-9679-b0880fa5cc46.png)

**Comment by bhariharan** [comment]
@rgoldiez Could you set a breakpoint on `line 100` in `SalesforceNetReactBridge.java`, on this line:

`String responseAsString = response.asString();`

Could you check if `response` is valid? Then, continue debugging inside `asString()` and check what happens in that method? It looks like that's where it's crapping out.

**Comment by rgoldiez** [comment]
@bhariharan - Forgive me as I am very new to the Android tools.  

I (think I) set a breakpoint to stop all threads at line 100 (see first screenshot).  It looks like it's still crapping out (second screenshot).

![image](https://cloud.githubusercontent.com/assets/10797610/17256650/0a154a48-5584-11e6-973c-f2c7a9f86074.png)

![image](https://cloud.githubusercontent.com/assets/10797610/17256620/f69c4d5e-5583-11e6-9b6f-f0e234f62718.png)

**Comment by wmathurin** [comment]
Should work now.
The problem was fixed by https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/1214
