### ISSUE TITLE
package.json start script fails on windows

### ISSUE THREAD

**Issue by JimBTek** [forcedotcom/SmartSyncExplorerReactNative#55]
for it to run on windows 10 in cmd.exe it needs to be:

`
 "scripts": {
    "start": "node_modules\\react-native\\packager\\packager.sh --root js"
  },
`

as per this article:  

http://www.reacttant.com/r/node/comments/4ix1jp/cant_run_npm_script_on_windows_10

**Comment by helenren** [comment]
@JimBTek Please pick up the fix from the branch to have a try. Please feel free to ping us if you still have issue or hit other issue. Thanks.
