### ISSUE TITLE
Crashes with SIGABRT/uncaught exception

### ISSUE THREAD

**Issue by pedramsaleh** [forcedotcom/SmartSyncExplorerReactNative#58]
Just installed this and when trying to get it running in Xcode, the salesforce logo comes up in the simulator, but then it crashes at the following line of code:

_int retVal = UIApplicationMain(argc, argv, @"SFApplication", @"AppDelegate");_

The last line of output is: _libc++abi.dylib: terminating with uncaught exception of type NSException_

The full output is here:
http://pastebin.com/G6kb8uGm

I'm using RN 30 and Xcode 8

**Comment by pedramsaleh** [comment]
It seems that SDK 4.3 and Xcode 8 don't fully get along right now. I was also getting the following error:

**\* Terminating app due to uncaught exception 'com.salesforce.security.keychainException', reason: 'writeToKeychain: Error adding keychain item: Unknown status code (-34018).'

Enabling Keychain Sharing under "Capabilities" will fix the problem.

![screen shot 2016-09-28 at 9 24 27 am](https://cloud.githubusercontent.com/assets/12803855/18915633/ac0cef9e-855f-11e6-9075-0f1bdd6f9fb0.png)

**Comment by khawkins** [comment]
You can track [Issue 1655](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/1655) on the main Mobile SDK repo, for updates on the simulator keychain issue.
