### ISSUE TITLE
Integration with existing app

### ISSUE THREAD

**Issue by SuhairZain** [forcedotcom/SmartSyncExplorerReactNative#90]
Hi,
We have an app for a client that uses SalesForce as backend and now the client wants to integrate push notifications into the app. From a search, I found that there's ample resources on how to create a new RN app with SF support using `forceios` command, IIRC. But there doesn't seem to be any documentation on how to add SF into an existing app.

Is there a way to integrate SF SDK into an existing RN app?

**Comment by wmathurin** [comment]
We use cocoapods on iOS for native and react native applications.
Use the [podfile](https://github.com/forcedotcom/SmartSyncExplorerReactNative/blob/master/ios/Podfile) from this sample app as a starting point. Make sure also to review the [AppDelegate.m](https://github.com/forcedotcom/SmartSyncExplorerReactNative/blob/master/ios/SmartSyncExplorerReactNative/AppDelegate.m) code.

@rwhitley do we have any documentation on this particular use case (integrating Mobile SDK into an existing application)?

**Comment by bhariharan** [comment]
Our `Android` libraries can be imported directly using `Maven` as explained in our dev guide [here](https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/android_update_maven.htm?search_text=gradle).

**Comment by bhariharan** [comment]
[Here](https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/entity_framework_native_add_ios.htm?search_text=cocoapods) is documentation on how to add our `iOS` libraries into an existing app using `Cocoapods`.

**Comment by SuhairZain** [comment]
Thank you for your comments, but how do I get notified on the react native side when a notification is received?

**Comment by bhariharan** [comment]
This forum is reserved for filing bugs/issues with our code. For other questions, please use our [Google+ community](https://plus.google.com/u/1/communities/114225252149514546445?cfem=1).
